### ISSUE TITLE
i think wrong link of application 

### ISSUE THREAD

**Issue by XAMIR555** [p32929/AndroidAppLockscreen#1]
hello sir 

according to my info you put the wrong link the discraption  of git hub project 

i see your git hub this is app lock screen repository but you put the link Dario - Diary, Journal, Notes, Mood Tracker so please check the link and verified me

**Comment by p32929** [comment]
I guess, you just misunderstood something. The description mentions that the Library UI is inspired by the app named Diaro. 

And the demo app you're talking about, is in the repository, not in the link.
