### ISSUE TITLE
Forgot password not implemented

### ISSUE THREAD

**Issue by picobulgarelli** [p32929/AndroidAppLockscreen#2]
When the user press "Forgot password?" the app crash with error:

`java.lang.IllegalStateException: Could not find method forgotPassword(View) in a parent or ancestor Context for android:onClick attribute defined on view class androidx.appcompat.widget.AppCompatTextView with id 'forgot_pass_textview'`

Please complete the code or would be better if you let the dev choose to hide this feature.

**Comment by p32929** [comment]
I totally forgot. Thanks for the reminder. I'll implement the feature soon.

**Comment by p32929** [comment]
Fixed :) Check out the new version ( 1.2 )
